ALTER TABLE player_stats
    ALTER COLUMN elo SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN elo_change SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN highest_elo SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN lowest_elo SET DATA TYPE DOUBLE PRECISION;


ALTER TABLE game_player_stats
    ALTER COLUMN elo_change SET DATA TYPE DOUBLE PRECISION;

ALTER TABLE league_config
    ALTER COLUMN starting_elo SET DATA TYPE DOUBLE PRECISION;

ALTER TABLE match_player_stats
    ALTER COLUMN elo_change SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN initial_elo SET DATA TYPE DOUBLE PRECISION;

ALTER TABLE match_player_stats_snapshot
    ALTER COLUMN elo SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN elo_change SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN highest_elo SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN lowest_elo SET DATA TYPE DOUBLE PRECISION;
